# This is a basic workflow to help you get started with Actions

name: CI-Coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Install gcov 
      run: sudo apt -y install gcovr
    - name: make coverage1
      run: make -C 3_Implementation/ coverage1


##############################

coverage:$(BUILD)
	gcc -fprofile-arcs -ftest-coverage $(TEST_SRC) $(INC) -o $(BUILD)/aout.$(EXEC)
	$(BUILD)/aout.$(EXEC)
	gcov -a test_loanCalculator.gcno
	$(RM) *.gcda
	$(RM) *.gcno
	$(RM) *c.gcov
